"""add ep val

Revision ID: 89572f2b3a64
Revises: cbb38cbff1ed
Create Date: 2024-03-19 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89572f2b3a64'
down_revision: Union[str, None] = 'cbb38cbff1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем колонку как nullable
    op.add_column('episodes', sa.Column('cost', sa.Float(), nullable=True))
    
    # Устанавливаем значение по умолчанию для существующих записей
    op.execute("UPDATE episodes SET cost = 15.0 WHERE cost IS NULL")
    
    # Теперь делаем колонку NOT NULL
    op.alter_column('episodes', 'cost',
               existing_type=sa.Float(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'cost')
    # ### end Alembic commands ###
