"""add Chapters

Revision ID: a6d1b0bcfd44
Revises: 94137e34dd1a
Create Date: 2025-05-10 13:20:52.767631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d1b0bcfd44'
down_revision: Union[str, None] = '94137e34dd1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('movie_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chapters', 'movies', ['movie_id'], ['movie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.drop_column('chapters', 'movie_id')
    # ### end Alembic commands ###
