"""add User val

Revision ID: cbb38cbff1ed
Revises: fb744ddcdad8
Create Date: 2025-05-11 16:05:37.731779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb38cbff1ed'
down_revision: Union[str, None] = 'fb744ddcdad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('premium_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('money', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'title')
    op.drop_column('users', 'level')
    op.drop_column('users', 'money')
    op.drop_column('users', 'premium_until')
    op.drop_column('users', 'is_premium')
    # ### end Alembic commands ###
