"""add Movie url

Revision ID: ea6759bf4547
Revises: 2025_05_09_create_login_attempts
Create Date: 2025-05-10 12:58:17.723488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea6759bf4547'
down_revision: Union[str, None] = '2025_05_09_create_login_attempts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_attempts_email_created_at', table_name='login_attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_login_attempts_email_created_at', 'login_attempts', ['email', 'created_at'], unique=False)
    # ### end Alembic commands ###
